In [5]:
import pandas as pd

In [6]:
pd.__version__

'3.0.6'

In [7]:
novalink_df = pd.read_csv('data/dataset.csv')

In [8]:
novalink_df.head()

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
0,CUST00001,SUB00001,PROD002,2348043756984,Customer 1,male,18-25,Kano,North West,premium,...,12000,2146,NaN,233,12000.0,NaN,4g,NaN,NaN,5.0
1,CUST00002,SUB00002,PROD004,2348095683063,Customer 2,NaN,26-35,Port Harcourt,North Central,NaN,...,35000,NaN,3162.0,291,35000.0,Card,3G,-77.0,0.0,3.0
2,CUST00003,SUB00003,PROD005,2348073190044,Customer 3,F,NaN,Lagos,North West,Standard,...,8000,45000MB,3030.0,416,NaN,Bank Transfer,4g,-78.0,1.0,NaN
3,CUST00004,SUB00004,PROD003,2348086724807,Customer 4,m,36-45,LAGOS,South West,Standard,...,18000,45000MB,NaN,5,NaN,Cash,4G,NaN,2.0,1.0
4,CUST00005,SUB00005,PROD002,2348073126385,Customer 5,FEMALE,26-35,Abuja,South East,Corporate,...,12000,NaN,NaN,510,12000.0,CARD,5G,-999.0,5.0,4.0

In [9]:
novalink_df.tail(2)

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
4998,CUST04999,SUB04999,PROD003,2348029950713,Customer 4999,NaN,NaN,NaN,North West,Standard,...,18000,NaN,NaN,462,NaN,Bank Transfer,3G,-71.0,0.0,5.0
4999,CUST05000,SUB05000,PROD002,2348081318684,Customer 5000,Female,60+,portharcourt,North West,NaN,...,12000,NaN,759.0,367,12000.0,Cash,4G,-68.0,2.0,4.0

In [10]:
novalink_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  5000 non-null   str
 1   subscription_id              5000 non-null   str
 2   product_id                   5000 non-null   str
 3   phone_number                 5000 non-null   int64
 4   customer_name                5000 non-null   str
 5   gender                       4548 non-null   str
 6   age_group                    4148 non-null   str
 7   city                         4551 non-null   str
 8   region                       5000 non-null   str
 9   customer_segment             4294 non-null   str
 10  subscription_start_date      5000 non-null   str
 11  subscription_status          4495 non-null   str
 12  plan_type                    5000 non-null   str
 13  contract_type                5000 non-null   str
 14  product_name                 5000 non-null   str
 15  product_category             5000 non-null   str
 16  monthly_price                5000 non-null   int64
 17  data_usage_mb                3336 non-null   str
 18  voice_minutes                2556 non-null   float64
 19  sms_count                    5000 non-null   int64
 20  monthly_bill                 3312 non-null   float64
 21  payment_method               4340 non-null   str
 22  network_type                 4160 non-null   str
 23  average_signal_strength_dbm  3297 non-null   float64
 24  complaints_count             4020 non-null   float64
 25  service_rating               4172 non-null   float64
dtypes: float64(5), int64(3), str(18)
memory usage: 1015.8 KB

In [11]:
novalink_df.head(10)

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
0,CUST00001,SUB00001,PROD002,2348043756984,Customer 1,male,18-25,Kano,North West,premium,...,12000,2146,NaN,233,12000.0,NaN,4g,NaN,NaN,5.0
1,CUST00002,SUB00002,PROD004,2348095683063,Customer 2,NaN,26-35,Port Harcourt,North Central,NaN,...,35000,NaN,3162.0,291,35000.0,Card,3G,-77.0,0.0,3.0
2,CUST00003,SUB00003,PROD005,2348073190044,Customer 3,F,NaN,Lagos,North West,Standard,...,8000,45000MB,3030.0,416,NaN,Bank Transfer,4g,-78.0,1.0,NaN
3,CUST00004,SUB00004,PROD003,2348086724807,Customer 4,m,36-45,LAGOS,South West,Standard,...,18000,45000MB,NaN,5,NaN,Cash,4G,NaN,2.0,1.0
4,CUST00005,SUB00005,PROD002,2348073126385,Customer 5,FEMALE,26-35,Abuja,South East,Corporate,...,12000,NaN,NaN,510,12000.0,CARD,5G,-999.0,5.0,4.0
5,CUST00006,SUB00006,PROD005,2348096853577,Customer 6,Male,26-35,Abuja,South South,Premium,...,8000,NaN,NaN,120,NaN,CARD,LTE,-82.0,2.0,2.0
6,CUST00007,SUB00007,PROD001,2348084767006,Customer 7,male,26-35,Abuja,North Central,Premium,...,25000,75753,NaN,355,NaN,USSD,4g,NaN,NaN,5.0
7,CUST00008,SUB00008,PROD004,2348059449170,Customer 8,Male,18-25,Ibadan,North Central,Basic,...,35000,NaN,NaN,202,NaN,Bank Transfer,5G,NaN,5.0,4.0
8,CUST00009,SUB00009,PROD004,2348092507943,Customer 9,MALE,36-45,Port Harcourt,South South,Corporate,...,35000,45000MB,2009.0,587,35000.0,CARD,3G,-999.0,2.0,3.0
9,CUST00010,SUB00010,PROD001,2348081845755,Customer 10,male,26-35,Ibadan,North Central,premium,...,25000,NaN,NaN,395,25000.0,bank transfer,3G,-999.0,5.0,2.0

In [12]:
novalink_df.shape

(5000, 26)

In [13]:
novalink_df_copy = novalink_df.copy()

In [14]:
novalink_df.head()

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
0,CUST00001,SUB00001,PROD002,2348043756984,Customer 1,male,18-25,Kano,North West,premium,...,12000,2146,NaN,233,12000.0,NaN,4g,NaN,NaN,5.0
1,CUST00002,SUB00002,PROD004,2348095683063,Customer 2,NaN,26-35,Port Harcourt,North Central,NaN,...,35000,NaN,3162.0,291,35000.0,Card,3G,-77.0,0.0,3.0
2,CUST00003,SUB00003,PROD005,2348073190044,Customer 3,F,NaN,Lagos,North West,Standard,...,8000,45000MB,3030.0,416,NaN,Bank Transfer,4g,-78.0,1.0,NaN
3,CUST00004,SUB00004,PROD003,2348086724807,Customer 4,m,36-45,LAGOS,South West,Standard,...,18000,45000MB,NaN,5,NaN,Cash,4G,NaN,2.0,1.0
4,CUST00005,SUB00005,PROD002,2348073126385,Customer 5,FEMALE,26-35,Abuja,South East,Corporate,...,12000,NaN,NaN,510,12000.0,CARD,5G,-999.0,5.0,4.0

In [15]:
novalink_df_copy.head()

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
0,CUST00001,SUB00001,PROD002,2348043756984,Customer 1,male,18-25,Kano,North West,premium,...,12000,2146,NaN,233,12000.0,NaN,4g,NaN,NaN,5.0
1,CUST00002,SUB00002,PROD004,2348095683063,Customer 2,NaN,26-35,Port Harcourt,North Central,NaN,...,35000,NaN,3162.0,291,35000.0,Card,3G,-77.0,0.0,3.0
2,CUST00003,SUB00003,PROD005,2348073190044,Customer 3,F,NaN,Lagos,North West,Standard,...,8000,45000MB,3030.0,416,NaN,Bank Transfer,4g,-78.0,1.0,NaN
3,CUST00004,SUB00004,PROD003,2348086724807,Customer 4,m,36-45,LAGOS,South West,Standard,...,18000,45000MB,NaN,5,NaN,Cash,4G,NaN,2.0,1.0
4,CUST00005,SUB00005,PROD002,2348073126385,Customer 5,FEMALE,26-35,Abuja,South East,Corporate,...,12000,NaN,NaN,510,12000.0,CARD,5G,-999.0,5.0,4.0

In [17]:
list(novalink_df.columns)

['customer_id',
 'subscription_id',
 'product_id',
 'phone_number',
 'customer_name',
 'gender',
 'age_group',
 'city',
 'region',
 'customer_segment',
 'subscription_start_date',
 'subscription_status',
 'plan_type',
 'contract_type',
 'product_name',
 'product_category',
 'monthly_price',
 'data_usage_mb',
 'voice_minutes',
 'sms_count',
 'monthly_bill',
 'payment_method',
 'network_type',
 'average_signal_strength_dbm',
 'complaints_count',
 'service_rating']

In [11]:
novalink_df.head()

,customer_id,subscription_id,product_id,phone_number,customer_name,gender,age_group,city,region,customer_segment,...,monthly_price,data_usage_mb,voice_minutes,sms_count,monthly_bill,payment_method,network_type,average_signal_strength_dbm,complaints_count,service_rating
0,CUST00001,SUB00001,PROD002,2348043756984,Customer 1,male,18-25,Kano,North West,premium,...,12000,2146,NaN,233,12000.0,NaN,4g,NaN,NaN,5.0
1,CUST00002,SUB00002,PROD004,2348095683063,Customer 2,NaN,26-35,Port Harcourt,North Central,NaN,...,35000,NaN,3162.0,291,35000.0,Card,3G,-77.0,0.0,3.0
2,CUST00003,SUB00003,PROD005,2348073190044,Customer 3,F,NaN,Lagos,North West,Standard,...,8000,45000MB,3030.0,416,NaN,Bank Transfer,4g,-78.0,1.0,NaN
3,CUST00004,SUB00004,PROD003,2348086724807,Customer 4,m,36-45,LAGOS,South West,Standard,...,18000,45000MB,NaN,5,NaN,Cash,4G,NaN,2.0,1.0
4,CUST00005,SUB00005,PROD002,2348073126385,Customer 5,FEMALE,26-35,Abuja,South East,Corporate,...,12000,NaN,NaN,510,12000.0,CARD,5G,-999.0,5.0,4.0

In [12]:
db_username = 'postgres'
password = 'password'
host = 'localhost'
port = '5432'
database = 'novalink_db'

from sqlalchemy import create_engine

engine = create_engine(f'postgresql+psycopg2://{db_username}:{password}@{host}:{port}/{database}')

table_name = 'novalink_data'

novalink_df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

1000